### ISSUE TITLE
Using PABLO with CFD

### ISSUE THREAD

**Issue by Haider-BA** [optimad/bitpit#1]
Hi,
Is it possible to use PABLO with lattice Boltzmann method, how?

Regards
Ali

**Comment by marcocisternino** [comment]
Hi Ali,
Thank you for your interest in PABLO, you are now a member of PABLO Users group.
However, PABLO has migrated as module in a larger HPC library called bitpit.
You can find bitpit web page at
http://optimad.github.io/bitpit/
I suggest you to take a look at the voloctree module, a wrap around PABLO. You can still use PABLO directly from bitpit, but please notice that the PABLO github repo at
https://github.com/optimad/PABLO
is no more maintained and moreover the PABLO in bitpit is more efficient and complete.
Voloctree, and PABLO, is an octree manager and gives you a way to implement this kind of mesh and to manage the data attached to it and the MPI communications.
PABLO has been already used in several CFD and elliptic solver codes and in a Boltzmann BGK one, directly or using voloctree.
Therefore, sure, you can use PABLO/bitpit for a Lattice Boltzmann code and we are interesting in following your development, if you want to share it.

Please, feel free to ask everything you want on PABLO Users group, on bitpit Github page or directly by mail.

Sincerely,
Marco


Ottieni Outlook per Android<https://aka.ms/ghei36>





Da: TheAnalyst
Inviato: lunedì 14 agosto, 11:03
Oggetto: [optimad/bitpit] Using PABLO with CFD (#1)
A: optimad/bitpit
Cc: Subscribed


Hi,
Is it possible to use PABLO with lattice Boltzmann method, how?
Regards
Ali

**Comment by ActarusG69** [comment]
Hi,
First I congratulate all of you guy for this project.  I also wish you a happy new year !

I am interested in using your library in the CFD/LBM context but I find some difficulties to understand the voloctree  class:
1) Is there a way to  generate a NXxNYxNZ mesh in which each cell can be refined using an octal strategy (AMR like) and  allowing to use the 2:1 balance functionality.  
2) Is it possible to reject cells/octants if not used. For instance in the case of the flow around a sphere or a cylinder where the cells/octants inside the solid do not  contribute to the computation.

I saw that the volcartesian class provides with the  NXxNYxNZ mesh generation capability but the octal/AMR like refinement is not accessible anymore: am I mistaken?
Maybe it is necessary to derive a new class but, if so,  I will need a confirmation and,  if possible, some help.

Best,
Hatem

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
