### ISSUE TITLE
Voloctree, VolCartesian or alternative class

### ISSUE THREAD

**Issue by ActarusG69** [optimad/bitpit#10]
Hi,
First I congratulate all of you guys for this project.  I also wish you a happy new year !

I am interested in using your library in the CFD/LBM context but I find some difficulties to understand the voloctree  class:
1) Is there a way to  generate a NXxNYxNZ mesh in which each cell can be refined using an octal strategy (AMR like) and  allowing to use the 2:1 balance functionality.  
2) Is it possible to reject cells/octants if not used. For instance in the case of the flow around a sphere or a cylinder where the cells/octants inside the solid do not  contribute to the computation.

I saw that the volcartesian class provides with the  NXxNYxNZ mesh generation capability but the octal/AMR like refinement is not accessible anymore: am I mistaken?
Maybe it is necessary to derive a new class but, if so,  I will need a confirmation and,  if possible, some help.

Best,
Hatem

_Originally posted by @ActarusG69 in https://github.com/optimad/bitpit/issues/1#issuecomment-454488259_

**Comment by ActarusG69** [comment]
Thank you, I'll give it a try!

Regards,
Hatem.

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
