### ISSUE TITLE
Read vtu file printed by bitbip

### ISSUE THREAD

**Issue by LucaVerzeroliUnibg** [optimad/bitpit#131]
HI,
i'm looking the results produced by bitpit in the test folder after running 'make test'.
I'm using paraview 5.8.0, 5.8.1 and 5.9.0 but I can't read the vtu files.

I get this error message:
```
ERROR: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_superbuild/build/superbuild/paraview/src/VTK/IO/XML/vtkXMLUnstructuredDataReader.cxx, line 745
vtkXMLUnstructuredGridReader (0x644f3f0): Cannot read cell data from Cells. Offsets and connectivity arrays must be the same type.
```
Can you help me? I'm using the bitpit version 1.5. (the same for the 1.6)

**Comment by LucaVerzeroliUnibg** [comment]
I've just tried with the version on git. and the problem has been solved. I'm able to read the files

**Comment by andrea-iob** [comment]
We plan to release a new version of bitpit (1.7) in February. If needed, I can backport the fix for reading VTK files with recent versions of ParaView to bitpit 1.6.

**Comment by LucaVerzeroliUnibg** [comment]
I can wait the new release. Thank you.
I would like to ask you one more thing. Is it possible to print vtk or vtu file in ASCII mode?

**Comment by andrea-iob** [comment]
The class PatchKernel only allows to print the mesh in appended binary format. 

However, if you are using the class VTK (module IO) for your own output, you can select the ASCII format using the function ```VTK::setCodex(VTKFormat format)``` where VTKFormat can be either ASCII or APPENDED (see test_IO_00001 for an example).

**Comment by LucaVerzeroliUnibg** [comment]
Thank you very much. I'm waiting for the new release.
