### ISSUE TITLE
ParaTree::getCenter for a ghost octant

### ISSUE THREAD

**Issue by pkestene** [optimad/bitpit#17]
Hello,

If i'm not mistaken currently, there is no API to get center coordinates for a ghost octant.

I can send a patch for that. 
Would you prefer a separate function call, or just keep current API and add a last default argument, a boolean stating if the octant should be considered regular or ghost .

**Comment by edoardolombardi** [comment]
Hi Pierre, 
thank you for your warning report and offer of development.
Actually, there is no a method to get center coordinates of a ghost octant by using its index. However, if you're not bound to use index, there is an API to get the center coordinates by using the pointer to the octant, indifferently if local or ghost octant, as argument.
Anyway, we thank you a if you can send the patch to add this interface method; coherently with other get methods for ghost with index as argument, maybe a separate function can be preferred.
