### ISSUE TITLE
Compiler warning -- nested loops with same index variable name

### ISSUE THREAD

**Issue by ptooley** [optimad/bitpit#19]
When building current master 1630f0f4cf I get the follow compiler warning:

```
bitpit/src/voloctree/voloctree.cpp(1774): warning #823: reference is to variable "k" (declared at line 1721) -- under old for-init scoping rules it would have been variable "k" (declared at line 1729)
                createdCells[k] = cellId;
```
It seems that there are are a pair of nested loops, both using the variable name "k" as their loop index.  

I suggest that the inner loop variable name should be changed (to "j"?), both to silence the warning and to make the code more explicit in intent.

**Comment by andrea-iob** [comment]
Fixed on master branch. Thanks.
