### ISSUE TITLE
patchkernel: Question - Most efficient way to make sure the vertex Ids & cell Ids are contiguous?

### ISSUE THREAD

**Issue by DMurataj01** [optimad/bitpit#200]
Hi - What would be the most efficient way to make sure the Vertex Ids & Cell Ids are contiguous in a patch?

Thanks,
Denis

**Comment by andrea-iob** [comment]
With contiguous you mean numbered from 0 to N - 1, where N is the number of cell/vertices, is this correct? 

The patch has the methods consecutiveRenumber*, that will make sure the ids are contiguous. However those methods are not optimized and will renumber the ids even it the ids are already contiguous.

If you only want to check if the ids are contiguous, the not-so-efficient way is to get the ids with patch.getCells().getIds(true) (where true means that the ids will be ordered) and then check if the last id (the greatest one) is equal to (nCells - 1). Or better, just iterate over the cells with a ConstCellIterator and find the maximum id (this will avoid allocating the vector with the ids).

There is a more efficient way to check if the ids are contiguous, but involves querying the id generator of the patch and this object is private. The index generator keeps track of the greatest id that was assigned to cells/vertices. Checking if the greatest assigned id is equal to N - 1 should do the trick. Do you thinks this will work, have I overlook something? If this method can work, we can consider adding new methods that tells if cells/vertices/interfaces numberings are contiguous (and using this new methods in consecutiveRenumber* to avoid renumbering ids if they are already contiguous).

**Comment by DMurataj01** [comment]
Thanks for your reply @andrea-iob - we've gone down the ConstCellIterator route at the moment but i think it would be very useful if you could add new methods to check if cells/vertices/interfaces are contiguous & also updating consecutiveRenumber.

Many Thanks!

Kind Regards,
Denis
