### ISSUE TITLE
getLastInternalVertex() inside patch_kernel class has declaration but no definition

### ISSUE THREAD

**Issue by kgkara** [optimad/bitpit#247]

**Comment by andrea-iob** [comment]
I've added the missing definition. May I ask you how you you plant to use the function? I'm asking because if you want to iterate over the internal vertices, you may want to use the iterators internalVertexBegin/internalVertexEnd or internalVertexConstBegin/internalVertexConstEnd.

**Comment by kgkara** [comment]
> I've added the missing definition. May I ask you how you you plant to use the function? I'm asking because if you want to iterate over the internal vertices, you may want to use the iterators internalVertexBegin/internalVertexEnd or internalVertexConstBegin/internalVertexConstEnd.

Thanks. I ended up not using this function, but something similar to what you mentioned (a wrapper around bitpit functions to check if vertex is interior with respect to the patch in the scope of the current rank).

**Comment by andrea-iob** [comment]
Consider that the bitpit::Vertex class has also the method isInterior.
