### ISSUE TITLE
PABLO ~ Update PABLO destructor message.

### ISSUE THREAD

**Issue by DMurataj01** [optimad/bitpit#255]
This message shows upon successful run of PABLO... I think it would be better to rename this message to something which indicates this runs successfully.

` PABLO :: ---------------------------------------------

PABLO :: --------------- R.I.P. PABLO ----------------

PABLO :: ---------------------------------------------

PABLO :: --------------------------------------------- `

**Comment by andrea-iob** [comment]
I agree that this message can be misleading. I think we can just remove it. If everything is running fine, there is no need to print a message when a PABLO object is destroyed.

**Comment by DMurataj01** [comment]
Yep I agree with you 👍
