### ISSUE TITLE
does bitpit support defining a domain with different lengths in different directions

### ISSUE THREAD

**Issue by Watchmojo** [optimad/bitpit#366]
does bitpit support defining a domain with different lengths in different directions, such as [0,1] X [0,3] X [0,5].

thank you

**Comment by andrea-iob** [comment]
If we are talking about the octree modules (PABLO or VolOctree), only square/cubic domains are supported (e.g. [0,3] X [0,3] X [0,3]).

**Comment by andrea-iob** [comment]
The unstructured mesh module (VolUnstructured) allows to use any domain shape, but the underlying data structures will be the ones of a generic unstructured mesh and they will not use an octree for refinement/partitioning/...

**Comment by DMurataj01** [comment]
@Watchmojo 

> does bitpit support defining a domain with different lengths in different directions, such as [0,1] X [0,3] X [0,5].
> 
> thank you

Some light modifications to PABLO i.e. changing the L to mL (double to darray3) and updating the logic that follows should get you there pretty quickly. You can then pipe this to VolUnstructured and should be able to use that

**Comment by Watchmojo** [comment]
Thanks.
