### ISSUE TITLE
Simplify DiscretizationStencil class

### ISSUE THREAD

**Issue by andrea-iob** [optimad/bitpit#65]
Current implementation of DiscretizationStencil class allows to store different set of stencils. Each stencil is stored in a different "bucket". This feature was used to store in one single data structure the stencils of the different interfaces of a cell.

Since some months, we no longer need DiscretizationStencil class being able to store different set of stencils. Can we remove this feature? @edoardolombardi @roccoarpa Are you relying on stencil buckets in your applications?

**Comment by roccoarpa** [comment]
@andrea-iob: I'm pretty sure we are not using them. But @edoardolombardi please correct me if I'm wrong.

**Comment by edoardolombardi** [comment]
No, we're not using them.

**Comment by andrea-iob** [comment]
Stencil "bucket" feature has been removed.
