### ISSUE TITLE
Interfaces getId from cell 

### ISSUE THREAD

**Issue by araeli** [optimad/bitpit#7]
Hi all, 

sorry to bother you, I can't find how to get the interfaces information from a Cell or an Octant. I can get the interfaces globally using getInterfaces(), moreover when I would examine the interfaces belonging on a cell I guess that I'm missing something.

Supposing four faces as example I use
`    for (int i=0;i<4;i++){

        long inter=cell.getInterface(i,ID);

        std::array<double,3> normal = mytree.evalInterfaceNormal(inter);

        cout << endl<< "index of face "<< inter<< endl << normal<<endl;

    }`

where ID is initialized to 0. When I print the normal vectors and the indices it is evident that I'm doing an error; can you example me the correct way to extract the index of the interfaces when two or more of them lie on the same face? Is the choice to initialize ID wrong?

I also tried to get the interfaces of the face using 
`long *inter=cell.getInterfaces(i);`
but I'm not sure about the correct use of the obtained pointer in interface-class functions.

Thank you for your help,
Alice

**Comment by andrea-iob** [comment]
Hi Alice,

to loop over the interfaces of a cell you can do something like:
'''
VolOctree patch = ...;

const Cell &cell = ...;

int nInterfaces = cell.getInterfaceCount();
const long *interfaces = cell.getInterfaces();
for(int n = 0; n < nInterfaces; ++n) {
    const long interfaceId = interfaces[n];

    std::array<double, 3> normal = patch->evalInterfaceNormal(interfaceId);
    ...
}
'''

Please note that PABLO interfaces and VolOctree interfaces are two different things. If you are working with VolOctree you have to evaluate interface properties using VolOctree functions (the same applies for Cells and Octants).

Andrea

**Comment by marcocisternino** [comment]
Hi everybody.
Alice, Andrea explained you how to loop over all the interface of a cell and normally this is what a user wants.
But I think, from what you wrote, that you don't need exactly this.
If I have understood, you want to loop in this way
loop over cells
  loop over cell faces
     loop over face interfaces

If this is correct, some overrides of the methods Andrea showed you can do the job.
I will mix some [pseudocode] to real bitpit calls

[loop over N cells:]
  int nFaces = cell.getFaceCount();
  for(int f=0; f < nFaces; ++f){
    int nInterfaceForFace = cell.getInterfaceCount(f);
    for(int i = 0; i < nInterfaceForFace; ++i){
      long intefaceID = cell.getInterface(f,i);
      [ask what you need about the interface using its ID, interfaceID. Normally, ask this to the patch]
    }
  }


So you have N cells in the patch, nFaces for each cell and nInterfaceForFace for any single face.
I hope it helps.
Cheers,

Marco Cisternino, PhD
marco.cisternino@optimad.it
_______________________________
OPTIMAD Engineering srl
Via Giacinto Collegno 18, Torino, Italia.
+3901119719782
www.optimad.it


________________________________________
Da: Andrea Iob <notifications@github.com>
Inviato: giovedì 29 marzo 2018 09:38:00
A: optimad/bitpit
Cc: Subscribed
Oggetto: Re: [optimad/bitpit] Interfaces getId from cell (#7)

Hi Alice,

to loop over the interfaces of a cell you can do something like:
'''
VolOctree patch = ...;

const Cell &cell = ...;

int nInterfaces = cell.getInterfaceCount();
const long *interfaces = cell.getInterfaces();
for(int n = 0; n < nInterfaces; ++n) {
const long interfaceId = interfaces[n];

std::array<double, 3> normal = patch->evalInterfaceNormal(interfaceId);
...


}
'''

Please note that PABLO interfaces and VolOctree interfaces are two different things. If you are working with VolOctree you have to evaluate interface properties using VolOctree functions (the same applies for Cells and Octants).

Andrea

**Comment by araeli** [comment]
Hi all,

Thanks for your quick help and your explanations! 
Marco fully understood the problem that I expressed not much clearly. 

Have a nice day,
Alice

**Comment by marcocisternino** [comment]
Alice, can we close the issue or you still need something else?

**Comment by araeli** [comment]
You can close, thank you again.
Best regards

**Comment by marcocisternino** [comment]
This issue has not seen any recent activity. I'm closing the issue, but feel free to re-open a closed issue if needed.
