### ISSUE TITLE
PABLO: findNeighbours missing elements with periodic boundary conditions and MPI

### ISSUE THREAD

**Issue by mdelorme** [optimad/bitpit#98]
Hi, 

I opened an issue a while ago on periodic conditions and border nodes in findNeighbours ([here](https://github.com/optimad/bitpit/issues/55)). We have just started working on a 3D version of our code, and the problem has started appearing again with multiple MPI processes.

If we take the example no11 in the ```examples``` folder, and add one more refinement level (see attachment, added a .txt extension so github would link it). Then, when we run with 4 mpi processes, some octants will be missing corner neighbours, but also edge neighbours. See attachment (log.rank1.txt), lines 117-118 for an example of missing nodes for a corner neighbour, and 395 for an edge neighbour.

The problem does not appear without MPI, so our take is that the periodic edges and corners are not included in the ghosts when loadbalancing. 

[PABLO_example_00011.cpp.txt](https://github.com/optimad/bitpit/files/5353261/PABLO_example_00011.cpp.txt)
[log.rank1.txt](https://github.com/optimad/bitpit/files/5353255/log.rank1.txt)

**Comment by marcocisternino** [comment]
Hello mdelorme,
thank you for the issue. I want to apologize for the answer delay, we are quite busy.
We have planned to solve the parallel periodic neighbors issue in the close future.
We understood the problem and we will work on it as soon as possible.
We will update you on the issue progress here.
Thanks again.

**Comment by mdelorme** [comment]
Hi Marco, 

No worries for the delay, and thank you for working on this :)

**Comment by andrea-iob** [comment]
Just to let you know that I'm working on this. I hope to have something to test for early next week.

**Comment by andrea-iob** [comment]
@mdelorme Could you please check if the branch "PABLO.fix.periodic.neighbours" fixes the problem? The branch starts from the current master, if needed I can prepare a branch that starts from 1.6. The changes are still experimental (I still doing some checks), but it would be great to have an early feedback from you.

**Comment by mdelorme** [comment]
Hi Andrea, 

We have tested the fix on our end and it seems the problem is gone !

Thanks a lot !
